global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 3h
  receiver: 'telegram-notifications'

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: ''
        chat_id: 
        message: |
          *Alert:* {{ .CommonAnnotations.summary }}
          {{ .CommonAnnotations.description }}
          *Status:* {{ .Status }}
          *Starts at:* {{ .StartsAt }}
