global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mysqld-exporter:9104']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.rules.yml
